### ISSUE TITLE
Proposed pain changes. 

### ISSUE THREAD

**Issue by jloustaunau** [DrZhivago1/DocPawnOverhaul#1]
<Patch>

    
    <Operation Class="PatchOperationSequence">
        <success>Always</success>
        <operations>
            
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="MissingBodyPart"]/injuryProps/painPerSeverity</xpath>
                <value>
                    <painPerSeverity>0.03</painPerSeverity>
                </value>
            </li>
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="MissingBodyPart"]/injuryProps/bleedRate</xpath>
                <value>
                    <bleedRate>0.30</bleedRate>
                </value>
            </li>
            
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="Misc"]/injuryProps/painPerSeverity</xpath>
                <value>
                    <painPerSeverity>0.0200</painPerSeverity>
                </value>
            </li>
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="Misc"]/injuryProps/bleedRate</xpath>
                <value>
                    <bleedRate>0.12</bleedRate>
                </value>
            </li>
            
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="Burn"]/injuryProps/painPerSeverity</xpath>
                <value>
                    <painPerSeverity>0.0200</painPerSeverity>
                </value>
            </li>
            
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="Crush"]/injuryProps/painPerSeverity</xpath>
                <value>
                    <painPerSeverity>0.0200</painPerSeverity>
                </value>
            </li>
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="Crush"]/injuryProps/bleedRate</xpath>
                <value>
                    <bleedRate>0.02</bleedRate>
                </value>
            </li>
            
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="Crack"]/injuryProps/painPerSeverity</xpath>
                <value>
                    <painPerSeverity>0.01</painPerSeverity>
                </value>
            </li>
            
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="Cut"]/injuryProps/painPerSeverity</xpath>
                <value>
                    <painPerSeverity>0.0200</painPerSeverity>
                </value>
            </li>
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="Cut"]/injuryProps/bleedRate</xpath>
                <value>
                    <bleedRate>0.12</bleedRate>
                </value>
            </li>
            
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="SurgicalCut"]/injuryProps/painPerSeverity</xpath>
                <value>
                    <painPerSeverity>0.0150</painPerSeverity>
                </value>
            </li>
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="SurgicalCut"]/injuryProps/bleedRate</xpath>
                <value>
                    <bleedRate>0.10</bleedRate>
                </value>
            </li>
            
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="Scratch"]/injuryProps/painPerSeverity</xpath>
                <value>
                    <painPerSeverity>0.0150</painPerSeverity>
                </value>
            </li>
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="Scratch"]/injuryProps/bleedRate</xpath>
                <value>
                    <bleedRate>0.10</bleedRate>
                </value>
            </li>
            
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="Bite"]/injuryProps/painPerSeverity</xpath>
                <value>
                    <painPerSeverity>0.0200</painPerSeverity>
                </value>
            </li>
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="Bite"]/injuryProps/bleedRate</xpath>
                <value>
                    <bleedRate>0.10</bleedRate>
                </value>
            </li>
            
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="Stab"]/injuryProps/painPerSeverity</xpath>
                <value>
                    <painPerSeverity>0.0200</painPerSeverity>
                </value>
            </li>
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="Stab"]/injuryProps/bleedRate</xpath>
                <value>
                    <bleedRate>0.11</bleedRate>
                </value>
            </li>
            
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="Gunshot"]/injuryProps/painPerSeverity</xpath>
                <value>
                    <painPerSeverity>0.0200</painPerSeverity>
                </value>
            </li>
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="Gunshot"]/injuryProps/bleedRate</xpath>
                <value>
                    <bleedRate>0.12</bleedRate>
                </value>
            </li>
            
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="Shredded"]/injuryProps/painPerSeverity</xpath>
                <value>
                    <painPerSeverity>0.0300</painPerSeverity>
                </value>
            </li>
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="Shredded"]/injuryProps/bleedRate</xpath>
                <value>
                    <bleedRate>0.20</bleedRate>
                </value>
            </li>
            
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="Bruise"]/injuryProps/painPerSeverity</xpath>
                <value>
                    <painPerSeverity>0.0150</painPerSeverity>
                </value>
            </li>
            
            <li Class="PatchOperationReplace">
                <xpath>/Defs/HediffDef[defName="Frostbite"]/injuryProps/painPerSeverity</xpath>
                <value>
                    <painPerSeverity>0.0200</painPerSeverity>
                </value>
            </li>
        </operations>
    </Operation>

</Patch>

**Comment by DrZhivago1** [comment]
Pain reworked
